<template>
  <v-row
    class="space-x-2"
    justify="end"
    no-gutters
  >
    <v-btn
      v-t="'message.button.link.community_convention'"
      variant="text"
      size="small"
      href="https://www.fduhole.com/license"
    ></v-btn>
    <v-btn
      v-t="'message.button.link.open_source_license'"
      variant="text"
      size="small"
      href="https://github.com/OpenTreeHole/auth_frontend/blob/master/LICENSE"
    ></v-btn>
    <v-btn
      v-t="'message.button.link.github'"
      variant="text"
      size="small"
      href="https://github.com/OpenTreeHole/"
    ></v-btn>
  </v-row>
</template>
